# Generated by Django 3.1 on 2020-08-09 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200809_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('postDate',)},
        ),
    ]
