# Generated by Django 3.1 on 2020-08-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200810_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text2',
            field=models.TextField(max_length=2000),
        ),
    ]
